Repository githru/githru-vscode-ext, pull requests merged in 2025-09, with the labels that each got.

#873 [feat] multithreads 함수 반영
  packages/vscode/src/extension.ts
  packages/vscode/src/test/utils/gitParallel.spec.ts
  packages/vscode/src/utils/gitParallel.ts
  packages/vscode/src/utils/gitUtil.ts
Labels: performance

#883 [docs]: view/CONTRIBUTING.md 파일 수정
  packages/view/CONTRIBUTING.md
Labels: docs

#902 FEAT(vibe): [MCP Tool] 리뷰어 추천 툴 개발
  packages/mcp/.gitignore
  packages/mcp/README.md
  packages/mcp/claude_desktop_config.json
  packages/mcp/package.json
  packages/mcp/smithery.yaml
  packages/mcp/src/common/types.ts
  packages/mcp/src/common/utils.ts
  packages/mcp/src/index.ts
  packages/mcp/src/server.ts
  packages/mcp/src/tool/contributorRecommender.ts
  packages/mcp/src/tool/featureImpactAnalyzer.ts
  packages/mcp/tsconfig.json
Labels: new feature, vibe

#898 refactor(view/engine): DI 컨테이너 마이그레이션 (tsyringe -> inversify)
  package-lock.json
  packages/analysis-engine/package.json
  packages/analysis-engine/src/container.ts
  packages/analysis-engine/src/index.ts
  packages/analysis-engine/src/pluginOctokit.ts
  packages/analysis-engine/src/serviceTokens.ts
  packages/view/package.json
  packages/view/src/App.tsx
  packages/view/src/container/index.ts
  packages/view/src/container/tokens.ts
  packages/view/src/ide/FakeIDEAdapter.ts
  packages/view/src/ide/VSCodeIDEAdapter.ts
  packages/view/src/index.prod.tsx
  packages/view/src/index.tsx
  packages/view/src/services/index.ts
  packages/view/webpack.prod.config.js
Labels: refactor
